---
swagger: '2.0'
info:
  version: 9.0.0
  title: PostgREST API
  description: standard public schema
host: 127.0.0.1:3000
basePath: "/"
schemes:
- http
consumes:
- application/json
- application/vnd.pgrst.object+json
- text/csv
produces:
- application/json
- application/vnd.pgrst.object+json
- text/csv
paths:
  "/":
    get:
      tags:
      - Introspection
      summary: OpenAPI description (this document)
      produces:
      - application/openapi+json
      - application/json
      responses:
        '200':
          description: OK
  "/schema_version":
    get:
      tags:
      - schema_version
      parameters:
      - "$ref": "#/parameters/select"
      - "$ref": "#/parameters/order"
      - "$ref": "#/parameters/range"
      - "$ref": "#/parameters/rangeUnit"
      - "$ref": "#/parameters/offset"
      - "$ref": "#/parameters/limit"
      - "$ref": "#/parameters/preferCount"
      responses:
        '200':
          schema:
            items:
              "$ref": "#/definitions/schema_version"
            type: array
          description: OK
        '206':
          description: Partial Content
    post:
      tags:
      - schema_version
      parameters:
      - "$ref": "#/parameters/body.schema_version"
      - "$ref": "#/parameters/select"
      - "$ref": "#/parameters/preferReturn"
      responses:
        '201':
          description: Created
    delete:
      tags:
      - schema_version
      parameters:
      - "$ref": "#/parameters/preferReturn"
      responses:
        '204':
          description: No Content
    patch:
      tags:
      - schema_version
      parameters:
      - "$ref": "#/parameters/body.schema_version"
      - "$ref": "#/parameters/preferReturn"
      responses:
        '204':
          description: No Content
definitions:
  schema_version:
    type: object
parameters:
  preferParams:
    name: Prefer
    description: Preference
    required: false
    in: header
    type: string
    enum:
    - params=single-object
  preferReturn:
    name: Prefer
    description: Preference
    required: false
    in: header
    type: string
    enum:
    - return=representation
    - return=minimal
    - return=none
  preferCount:
    name: Prefer
    description: Preference
    required: false
    in: header
    type: string
    enum:
    - count=none
  select:
    name: select
    description: Filtering Columns
    required: false
    in: query
    type: string
  on_conflict:
    name: on_conflict
    description: On Conflict
    required: false
    in: query
    type: string
  order:
    name: order
    description: Ordering
    required: false
    in: query
    type: string
  range:
    name: Range
    description: Limiting and Pagination
    required: false
    in: header
    type: string
  rangeUnit:
    name: Range-Unit
    description: Limiting and Pagination
    required: false
    default: items
    in: header
    type: string
  offset:
    name: offset
    description: Limiting and Pagination
    required: false
    in: query
    type: string
  limit:
    name: limit
    description: Limiting and Pagination
    required: false
    in: query
    type: string
  body.schema_version:
    name: schema_version
    description: schema_version
    required: false
    schema:
      "$ref": "#/definitions/schema_version"
    in: body
externalDocs:
  url: https://postgrest.org/en/v9.0/api.html
  description: PostgREST Documentation
