components:
  schemas:
    AppStatus:
      properties:
        appVersionInfo:
          $ref: '#/components/schemas/AppVersion'
        pgbouncerWorking:
          type: boolean
        postgresWorking:
          type: boolean
        triggers:
          items:
            $ref: '#/components/schemas/AppTrigger'
          type: array
      required:
      - postgresWorking
      - pgbouncerWorking
      - triggers
      - appVersionInfo
      type: object
    AppTrigger:
      properties:
        triggerEventManipulation:
          type: string
        triggerEventTable:
          type: string
        triggerName:
          type: string
      required:
      - triggerEventTable
      - triggerName
      - triggerEventManipulation
      type: object
    AppVersion:
      properties:
        appCommit:
          type: string
        appVersion:
          type: string
        envName:
          $ref: '#/components/schemas/BuildEnvironment'
      required:
      - appVersion
      - appCommit
      - envName
      type: object
    BuildEnvironment:
      enum:
      - ProductionEnv
      - StagingEnv
      - TestEnv
      - BetaEnv
      type: string
    DiffTime:
      format: PyYmMdDThHmMs[.sss]S
      type: string
    Param:
      description: type is either int8 or str
      format: value:type
      type: string
    SqlDebugOutput:
      properties:
        dCompileTime:
          format: double
          type: number
        dEXPLAIN:
          items:
            type: string
          type: array
        dOrigSQL:
          type: string
        dParams:
          items:
            $ref: '#/components/schemas/Param'
          type: array
        dSQL:
          type: string
      required:
      - dSQL
      - dOrigSQL
      - dParams
      - dCompileTime
      - dEXPLAIN
      type: object
    WalletDebugOutput:
      properties:
        walletCount:
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          type: integer
      required:
      - walletCount
      type: object
info:
  description: This is an API for the StreamChain service
  license:
    name: MIT
  title: StreamChain API
  version: '1.0'
openapi: 3.0.0
paths:
  /admin/db_size:
    get:
      responses:
        '200':
          content:
            application/json;charset=utf-8:
              schema:
                type: string
          description: ''
  /admin/sync_status/behind_by:
    get:
      responses:
        '200':
          content:
            application/json;charset=utf-8:
              schema:
                $ref: '#/components/schemas/DiffTime'
          description: ''
  /api/debug/sql:
    post:
      parameters:
      - in: query
        name: blocks
        required: false
        schema:
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          type: integer
      - in: query
        name: params
        schema:
          items:
            description: type is either int8 or str
            format: value:type
            type: string
          type: array
      requestBody:
        content:
          text/plain;charset=utf-8:
            schema:
              type: string
      responses:
        '200':
          content:
            application/json;charset=utf-8:
              schema:
                $ref: '#/components/schemas/SqlDebugOutput'
          description: ''
        '400':
          description: Invalid `params` or `blocks` or `body`
  /api/debug/wallets:
    post:
      responses:
        '200':
          content:
            application/json;charset=utf-8:
              schema:
                $ref: '#/components/schemas/WalletDebugOutput'
          description: ''
  /api/status:
    get:
      responses:
        '200':
          content:
            application/json;charset=utf-8:
              schema:
                $ref: '#/components/schemas/AppStatus'
          description: ''
  /api/v1/dynamic/query:
    post:
      parameters:
      - in: query
        name: blocks
        required: false
        schema:
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          type: integer
      - in: query
        name: params
        schema:
          items:
            description: type is either int8 or str
            format: value:type
            type: string
          type: array
      requestBody:
        content:
          text/plain;charset=utf-8:
            schema:
              type: string
      responses:
        '200':
          content:
            application/json;charset=utf-8:
              schema:
                description: Arbitrary json
                title: json
          description: ''
        '400':
          description: Invalid `params` or `blocks` or `body`
  /api/v1/dynamic/sse:
    post:
      responses:
        '200':
          content:
            text/event-stream:
              schema:
                description: A server-sent event stream. This isn't strictly compatible
                  with OpenApi spec. Also see https://html.spec.whatwg.org/multipage/server-sent-events.html#server-sent-events
                format: event-stream
                items:
                  properties:
                    data:
                      description: Arbitrary json
                      title: json
                    event:
                      enum:
                      - new_block
                      - rollback
                      type: string
                  type: object
                type: array
          description: Returns events describing new blocks
      summary: Listen to new blocks on the chain
    summary: Server-sent events for new blocks
  /api/v1/static/last/block:
    get:
      responses:
        '200':
          content:
            application/json;charset=utf-8:
              schema:
                maximum: 9223372036854775807
                minimum: -9223372036854775808
                type: integer
          description: ''
  /api/v1/static/last/slot_no:
    get:
      responses:
        '200':
          content:
            application/json;charset=utf-8:
              schema:
                maximum: 9223372036854775807
                minimum: -9223372036854775808
                type: integer
          description: ''
  /api/v1/static/last/tx:
    get:
      parameters:
      - in: query
        name: script
        required: false
        schema:
          type: string
      responses:
        '200':
          content:
            application/json;charset=utf-8:
              schema:
                type: string
          description: ''
        '400':
          description: Invalid `script`
  /api/v1/static/sse/blocks: {}
