components:
  schemas:
    AppStatus:
      properties:
        appVersionInfo:
          $ref: '#/components/schemas/AppVersion'
        pgbouncerWorking:
          $ref: '#/components/schemas/ComponentStatus'
        postgresWorking:
          $ref: '#/components/schemas/ComponentStatus'
        triggers:
          items:
            $ref: '#/components/schemas/AppTrigger'
          type: array
        wcontrollerStatus:
          $ref: '#/components/schemas/WalletControllerStatus'
      required:
      - postgresWorking
      - pgbouncerWorking
      - wcontrollerStatus
      - triggers
      - appVersionInfo
      type: object
    AppTrigger:
      properties:
        triggerEventManipulation:
          type: string
        triggerEventTable:
          type: string
        triggerName:
          type: string
      required:
      - triggerEventTable
      - triggerName
      - triggerEventManipulation
      type: object
    AppVersion:
      properties:
        appCommit:
          type: string
        appVersion:
          type: string
        envName:
          $ref: '#/components/schemas/BuildEnvironment'
      required:
      - appVersion
      - appCommit
      - envName
      type: object
    BuildEnvironment:
      enum:
      - ProductionEnv
      - StagingEnv
      - TestEnv
      - BetaEnv
      type: string
    ComponentStatus:
      oneOf:
      - type: string
      - type: string
      type: object
    CustomQueryResult:
      oneOf:
      - properties:
          blockBlockNo:
            maximum: 9223372036854775807
            minimum: -9223372036854775808
            type: integer
          blockEpochNo:
            maximum: 9223372036854775807
            minimum: -9223372036854775808
            type: integer
          blockEpochSlotNo:
            maximum: 9223372036854775807
            minimum: -9223372036854775808
            type: integer
          blockHash:
            type: string
          blockId:
            maximum: 9223372036854775807
            minimum: -9223372036854775808
            type: integer
          blockOpCert:
            type: string
          blockOpCertCounter:
            maximum: 9223372036854775807
            minimum: -9223372036854775808
            type: integer
          blockPreviousId:
            maximum: 9223372036854775807
            minimum: -9223372036854775808
            type: integer
          blockProtoMajor:
            maximum: 9223372036854775807
            minimum: -9223372036854775808
            type: integer
          blockProtoMinor:
            maximum: 9223372036854775807
            minimum: -9223372036854775808
            type: integer
          blockSize:
            maximum: 9223372036854775807
            minimum: -9223372036854775808
            type: integer
          blockSlotLeaderId:
            maximum: 9223372036854775807
            minimum: -9223372036854775808
            type: integer
          blockSlotNo:
            maximum: 9223372036854775807
            minimum: -9223372036854775808
            type: integer
          blockTime:
            type: string
          blockTxCount:
            maximum: 9223372036854775807
            minimum: -9223372036854775808
            type: integer
          blockVrfKey:
            type: string
        required:
        - blockBlockNo
        - blockEpochNo
        - blockEpochSlotNo
        - blockHash
        - blockId
        - blockPreviousId
        - blockProtoMajor
        - blockProtoMinor
        - blockSize
        - blockSlotLeaderId
        - blockSlotNo
        - blockTime
        - blockTxCount
        type: object
      - properties:
          txBlockId:
            maximum: 9223372036854775807
            minimum: -9223372036854775808
            type: integer
          txBlockIndex:
            maximum: 9223372036854775807
            minimum: -9223372036854775808
            type: integer
          txDeposit:
            maximum: 9223372036854775807
            minimum: -9223372036854775808
            type: integer
          txFee:
            maximum: 9223372036854775807
            minimum: -9223372036854775808
            type: integer
          txHash:
            type: string
          txId:
            maximum: 9223372036854775807
            minimum: -9223372036854775808
            type: integer
          txInvalidBefore:
            format: double
            type: number
          txInvalidHereafter:
            format: double
            type: number
          txOutSum:
            maximum: 9223372036854775807
            minimum: -9223372036854775808
            type: integer
          txScriptSize:
            maximum: 9223372036854775807
            minimum: -9223372036854775808
            type: integer
          txSize:
            maximum: 9223372036854775807
            minimum: -9223372036854775808
            type: integer
          txValidContract:
            type: boolean
        required:
        - txBlockId
        - txBlockIndex
        - txDeposit
        - txFee
        - txHash
        - txId
        - txOutSum
        - txScriptSize
        - txSize
        - txValidContract
        type: object
      - description: Arbitrary json
        title: json
      type: object
    DiffTime:
      format: PyYmMdDThHmMs[.sss]S
      type: string
    Param:
      description: type is either int8 or str
      format: value:type
      type: string
    SqlDebugOutput:
      properties:
        dCompileTime:
          format: double
          type: number
        dEXPLAIN:
          items:
            type: string
          type: array
        dOrigSQL:
          type: string
        dParams:
          items:
            $ref: '#/components/schemas/Param'
          type: array
        dSQL:
          type: string
      required:
      - dSQL
      - dOrigSQL
      - dParams
      - dCompileTime
      - dEXPLAIN
      type: object
    WalletControllerStatus:
      properties:
        walletCount:
          $ref: '#/components/schemas/ComponentStatus'
        walletCreationCycle:
          $ref: '#/components/schemas/ComponentStatus'
      required:
      - walletCount
      - walletCreationCycle
      type: object
info:
  description: This is an API for the StreamChain service
  license:
    name: MIT
  title: StreamChain API
  version: '1.0'
openapi: 3.0.0
paths:
  /admin/db_size:
    get:
      responses:
        '200':
          content:
            application/json;charset=utf-8:
              schema:
                type: string
          description: ''
  /admin/sync_status/behind_by:
    get:
      responses:
        '200':
          content:
            application/json;charset=utf-8:
              schema:
                $ref: '#/components/schemas/DiffTime'
          description: ''
  /api/debug/sql:
    post:
      parameters:
      - in: query
        name: blocks
        required: false
        schema:
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          type: integer
      - in: query
        name: params
        schema:
          items:
            description: type is either int8 or str
            format: value:type
            type: string
          type: array
      requestBody:
        content:
          text/plain;charset=utf-8:
            schema:
              type: string
      responses:
        '200':
          content:
            application/json;charset=utf-8:
              schema:
                $ref: '#/components/schemas/SqlDebugOutput'
          description: ''
        '400':
          description: Invalid `params` or `blocks` or `body`
  /api/debug/wallets:
    post:
      responses:
        '200':
          content:
            application/json;charset=utf-8:
              schema:
                type: string
          description: ''
  /api/status:
    get:
      responses:
        '200':
          content:
            application/json;charset=utf-8:
              schema:
                $ref: '#/components/schemas/AppStatus'
          description: ''
  /api/v1/dynamic/query:
    post:
      parameters:
      - in: query
        name: blocks
        required: false
        schema:
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          type: integer
      - in: query
        name: params
        schema:
          items:
            description: type is either int8 or str
            format: value:type
            type: string
          type: array
      requestBody:
        content:
          text/plain;charset=utf-8:
            schema:
              type: string
      responses:
        '200':
          content:
            application/json;charset=utf-8:
              schema:
                items:
                  $ref: '#/components/schemas/CustomQueryResult'
                type: array
          description: ''
        '400':
          description: Invalid `params` or `blocks` or `body`
  /api/v1/dynamic/sse:
    post:
      responses:
        '200':
          content:
            text/event-stream:
              schema:
                description: A server-sent event stream. This isn't strictly compatible
                  with OpenApi spec. Also see https://html.spec.whatwg.org/multipage/server-sent-events.html#server-sent-events
                format: event-stream
                items:
                  properties:
                    data:
                      description: Arbitrary json
                      title: json
                    event:
                      enum:
                      - new_block
                      - rollback
                      type: string
                  type: object
                type: array
          description: Returns events describing new blocks
      summary: Listen to new blocks on the chain
    summary: Server-sent events for new blocks
  /api/v1/static/last/block:
    get:
      responses:
        '200':
          content:
            application/json;charset=utf-8:
              schema:
                maximum: 9223372036854775807
                minimum: -9223372036854775808
                type: integer
          description: ''
  /api/v1/static/last/slot_no:
    get:
      responses:
        '200':
          content:
            application/json;charset=utf-8:
              schema:
                maximum: 9223372036854775807
                minimum: -9223372036854775808
                type: integer
          description: ''
  /api/v1/static/last/tx:
    get:
      parameters:
      - in: query
        name: script
        required: false
        schema:
          type: string
      responses:
        '200':
          content:
            application/json;charset=utf-8:
              schema:
                type: string
          description: ''
        '400':
          description: Invalid `script`
  /api/v1/static/sse/blocks: {}
